#!/usr/bin/env python3
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
from window import Window

main_window = Window()
main_window.connect("destroy", Gtk.main_quit)

Gtk.main()
