#!/usr/bin/env python3
import os
import sys
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

# Make sure we're always in the right directory
LAUNCH_PATH = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, LAUNCH_PATH)
os.chdir(LAUNCH_PATH)
from window import Window

# Create the window
main_window = Window()
main_window.connect("destroy", Gtk.main_quit)

# Launch the application
Gtk.main()
